const allPays = [
    {code: 'AFG', nom: 'Afghanistan'},
    {code: 'ALA', nom: 'Åland Islands'},
    {code: 'ALB', nom: 'Albanie'},
    {code: 'DZA', nom: 'Algérie'},
    {code: 'ASM', nom: 'Samoa'},
    {code: 'AND', nom: 'Andorre'},
    {code: 'AGO', nom: 'Angola'},
    {code: 'AIA', nom: 'Anguilla'},
    {code: 'ATA', nom: 'Antarctique'},
    {code: 'ATG', nom: 'Antigua et Barbuda'},
    {code: 'ARG', nom: 'Argentine'},
    {code: 'ARM', nom: 'Arménie'},
    {code: 'ABW', nom: 'Aruba'},
    {code: 'AUS', nom: 'Australie'},
    {code: 'AUT', nom: 'Autriche'},
    {code: 'AZE', nom: 'Azerbaïdjan'},
    {code: 'BHS', nom: 'Bahamas'},
    {code: 'BHR', nom: 'Bahrain'},
    {code: 'BGD', nom: 'Bangladesh'},
    {code: 'BRB', nom: 'Barbade'},
    {code: 'BLR', nom: 'Belarus'},
    {code: 'BEL', nom: 'Belgique'},
    {code: 'BLZ', nom: 'Belize'},
    {code: 'BEN', nom: 'Bénin'},
    {code: 'BMU', nom: 'Bermuda'},
    {code: 'BTN', nom: 'Bhutan'},
    {code: 'BOL', nom: 'Bolivie'},
    {code: 'BES', nom: 'Bonaire, Saint-Eustache et Saba'},
    {code: 'BIH', nom: 'Bosnie-Herzégovine'},
    {code: 'BWA', nom: 'Botswana'},
    {code: 'BVT', nom: 'Île Bouvet'},
    {code: 'BRA', nom: 'Brésil'},
    {code: 'IOT', nom: "Territoire britannique de l'océan Indien"},
    {code: 'BRN', nom: 'Brunéi Darussalam'},
    {code: 'BGR', nom: 'Bulgarie'},
    {code: 'BFA', nom: 'Burkina Faso'},
    {code: 'BDI', nom: 'Burundi'},
    {code: 'KHM', nom: 'Cambodge'},
    {code: 'CMR', nom: 'Cameroun'},
    {code: 'CAN', nom: 'Canada'},
    {code: 'CPV', nom: 'Cap-Vert'},
    {code: 'CYM', nom: 'Îles Caïmans'},
    {code: 'CAF', nom: 'République centrafricaine'},
    {code: 'TCD', nom: 'Tchad'},
    {code: 'CHL', nom: 'Chili'},
    {code: 'CHN', nom: 'Chine'},
    {code: 'CXR', nom: 'Île Christmas'},
    {code: 'CCK', nom: 'Îles Cocos (Keeling)'},
    {code: 'COL', nom: 'Colombie'},
    {code: 'COM', nom: 'Comores'},
    {code: 'COG', nom: 'Congo'},
    {code: 'COD', nom: 'Congo, République démocratique du Congo'},
    {code: 'COK', nom: 'Îles Cook'},
    {code: 'CRI', nom: 'Costa Rica'},
    {code: 'CIV', nom: "Côte d'Ivoire"},
    {code: 'HRV', nom: 'Croatie'},
    {code: 'CUB', nom: 'Cuba'},
    {code: 'CUW', nom: 'Curaçao'},
    {code: 'CYP', nom: 'Chypre'},
    {code: 'CZE', nom: 'République tchèque'},
    {code: 'DNK', nom: 'Danemark'},
    {code: 'DJI', nom: 'Djibouti'},
    {code: 'DMA', nom: 'Dominique'},
    {code: 'DOM', nom: 'République dominicaine'},
    {code: 'ECU', nom: 'Équateur'},
    {code: 'EGY', nom: 'Égypte'},
    {code: 'SLV', nom: 'El Salvador'},
    {code: 'GNQ', nom: 'Guinée équatoriale'},
    {code: 'ERI', nom: 'Érythrée'},
    {code: 'EST', nom: 'Estonie'},
    {code: 'ETH', nom: 'Éthiopie'},
    {code: 'FLK', nom: 'Îles Falkland (Malvinas)'},
    {code: 'FRO', nom: 'Îles Féroé'},
    {code: 'FJI', nom: 'Fidji'},
    {code: 'FIN', nom: 'Finlande'},
    {code: 'FR', nom: 'France'},
    {code: 'GUF', nom: 'Guyane française'},
    {code: 'PYF', nom: 'Polynésie française'},
    {code: 'ATF', nom: 'Terres australes françaises'},
    {code: 'GAB', nom: 'Gabon'},
    {code: 'GMB', nom: 'Gambie'},
    {code: 'GEO', nom: 'Géorgie'},
    {code: 'DEU', nom: 'Allemagne'},
    {code: 'GHA', nom: 'Ghana'},
    {code: 'GIB', nom: 'Gibraltar'},
    {code: 'GRC', nom: 'Grèce'},
    {code: 'GRL', nom: 'Groenland'},
    {code: 'GRD', nom: 'Grenade'},
    {code: 'GLP', nom: 'Guadeloupe'},
    {code: 'GUM', nom: 'Guam'},
    {code: 'GTM', nom: 'Guatemala'},
    {code: 'GGY', nom: 'Guernesey'},
    {code: 'GIN', nom: 'Guinée'},
    {code: 'GNB', nom: 'Guinée-Bissau'},
    {code: 'GUY', nom: 'Guyane'},
    {code: 'HTI', nom: 'Haïti'},
    {code: 'HMD', nom: 'Île Heard et îles McDonald'},
    {code: 'VAT', nom: 'Saint-Siège (État de la Cité du Vatican)'},
    {code: 'HND', nom: 'Honduras'},
    {code: 'HKG', nom: 'Hong Kong'},
    {code: 'HUN', nom: 'Hongrie'},
    {code: 'ISL', nom: 'Islande'},
    {code: 'IND', nom: 'Inde'},
    {code: 'IDN', nom: 'Indonésie'},
    {code: 'IRN', nom: "Iran, République islamique d Iran'"},
    {code: 'IRQ', nom: 'Irak'},
    {code: 'IRL', nom: 'Irlande'},
    {code: 'IMN', nom: 'Île de Man'},
    {code: 'ISR', nom: 'Israël'},
    {code: 'ITA', nom: 'Italie'},
    {code: 'JAM', nom: 'Jamaïque'},
    {code: 'JPN', nom: 'Japon'},
    {code: 'JEY', nom: 'Jersey'},
    {code: 'JOR', nom: 'Jordanie'},
    {code: 'KAZ', nom: 'Kazakhstan'},
    {code: 'KEN', nom: 'Kenya'},
    {code: 'KIR', nom: 'Kiribati'},
    {code: 'PRK', nom: 'Corée, République populaire démocratique de Corée'},
    {code: 'KOR', nom: 'Corée, République de Corée'},
    {code: 'KWT', nom: 'Koweït'},
    {code: 'KGZ', nom: 'Kirghizistan'},
    {code: 'LAO', nom: 'République démocratique populaire lao'},
    {code: 'LVA', nom: 'Lettonie'},
    {code: 'LBN', nom: 'Liban'},
    {code: 'LSO', nom: 'Lesotho'},
    {code: 'LBR', nom: 'Liberia'},
    {code: 'LBY', nom: 'Libye'},
    {code: 'LIE', nom: 'Liechtenstein'},
    {code: 'LTU', nom: 'Lituanie'},
    {code: 'LUX', nom: 'Luxembourg'},
    {code: 'MAC', nom: 'Macao'},
    {code: 'MKD', nom: 'Macédoine, ancienne République de Yougoslavie'},
    {code: 'MG', nom: 'Madagascar'},
    {code: 'MWI', nom: 'Malawi'},
    {code: 'MYS', nom: 'Malaisie'},
    {code: 'MDV', nom: 'Maldives'},
    {code: 'MLI', nom: 'Mali'},
    {code: 'MLT', nom: 'Malte'},
    {code: 'MHL', nom: 'Îles Marshall'},
    {code: 'MTQ', nom: 'Martinique'},
    {code: 'MRT', nom: 'Mauritanie'},
    {code: 'MUS', nom: 'Maurice'},
    {code: 'MYT', nom: 'Mayotte'},
    {code: 'MEX', nom: 'Mexique'},
    {code: 'FSM', nom: 'Micronésie, États fédérés de Micronésie'},
    {code: 'MDA', nom: 'Moldavie, République de Moldavie'},
    {code: 'MCO', nom: 'Monaco'},
    {code: 'MNG', nom: 'Mongolie'},
    {code: 'MNE', nom: 'Monténégro'},
    {code: 'MSR', nom: 'Montserrat'},
    {code: 'MAR', nom: 'Maroc'},
    {code: 'MOZ', nom: 'Mozambique'},
    {code: 'MMR', nom: 'Myanmar'},
    {code: 'NAM', nom: 'Namibie'},
    {code: 'NRU', nom: 'Nauru'},
    {code: 'NPL', nom: 'Népal'},
    {code: 'NLD', nom: 'Pays-Bas'},
    {code: 'NCL', nom: 'Nouvelle-Calédonie'},
    {code: 'NZL', nom: 'Nouvelle-Zélande'},
    {code: 'NIC', nom: 'Nicaragua'},
    {code: 'NER', nom: 'Niger'},
    {code: 'NGA', nom: 'Nigéria'},
    {code: 'NIU', nom: 'Niue'},
    {code: 'NFK', nom: 'Île Norfolk'},
    {code: 'MNP', nom: 'Îles Mariannes du Nord'},
    {code: 'NOR', nom: 'Norvège'},
    {code: 'OMN', nom: 'Oman'},
    {code: 'PAK', nom: 'Pakistan'},
    {code: 'PLW', nom: 'Palau'},
    {code: 'PSE', nom: 'Territoire palestinien occupé'},
    {code: 'PAN', nom: 'Panama'},
    {code: 'PNG', nom: 'Papouasie-Nouvelle-Guinée'},
    {code: 'PRY', nom: 'Paraguay'},
    {code: 'PER', nom: 'Pérou'},
    {code: 'PHL', nom: 'Philippines'},
    {code: 'PCN', nom: 'Pitcairn'},
    {code: 'POL', nom: 'Pologne'},
    {code: 'PRT', nom: 'Portugal'},
    {code: 'PRI', nom: 'Porto Rico'},
    {code: 'QAT', nom: 'Qatar'},
    {code: 'REU', nom: 'Réunion'},
    {code: 'ROU', nom: 'Roumanie'},
    {code: 'RUS', nom: 'Fédération de Russie'},
    {code: 'RWA', nom: 'Rwanda'},
    {code: 'BLM', nom: 'Saint Barthélemy'},
    {code: 'SHN', nom: 'Sainte-Hélène, Ascension et Tristan da Cunha'},
    {code: 'KNA', nom: 'Saint-Kitts-et-Nevis'},
    {code: 'LCA', nom: 'Sainte-Lucie'},
    {code: 'MAF', nom: 'Saint-Martin (partie française)'},
    {code: 'SPM', nom: 'Saint-Pierre-et-Miquelon'},
    {code: 'VCT', nom: 'Saint-Vincent-et-les Grenadines'},
    {code: 'WSM', nom: 'Samoa'},
    {code: 'SMR', nom: 'Saint-Marin'},
    {code: 'STP', nom: 'Sao Tomé-et-Principe'},
    {code: 'SAU', nom: 'Arabie saoudite'},
    {code: 'SEN', nom: 'Sénégal'},
    {code: 'SRB', nom: 'Serbie'},
    {code: 'SYC', nom: 'Seychelles'},
    {code: 'SLE', nom: 'Sierra Leone'},
    {code: 'SGP', nom: 'Singapour'},
    {code: 'SXM', nom: 'Sint Maarten (partie néerlandaise)'},
    {code: 'SVK', nom: 'Slovaquie'},
    {code: 'SVN', nom: 'Slovénie'},
    {code: 'SLB', nom: 'Îles Salomon'},
    {code: 'SOM', nom: 'Somalie'},
    {code: 'ZAF', nom: 'Afrique du Sud'},
    {code: 'SGS', nom: 'Géorgie du Sud et îles Sandwich du Sud'},
    {code: 'SSD', nom: 'Soudan du Sud'},
    {code: 'ESP', nom: 'Espagne'},
    {code: 'LKA', nom: 'Sri Lanka'},
    {code: 'SDN', nom: 'Soudan'},
    {code: 'SUR', nom: 'Suriname'},
    {code: 'SJM', nom: 'Svalbard et Jan Mayen'},
    {code: 'SWZ', nom: 'Swaziland'},
    {code: 'SWE', nom: 'Suède'},
    {code: 'CHE', nom: 'Suisse'},
    {code: 'SYR', nom: 'République arabe syrienne'},
    {code: 'TWN', nom: 'Taïwan, province de Chine'},
    {code: 'TJK', nom: 'Tadjikistan'},
    {code: 'TZA', nom: 'Tanzanie, République-Unie de Tanzanie'},
    {code: 'THA', nom: 'Thaïlande'},
    {code: 'TLS', nom: 'Timor-Leste'},
    {code: 'TGO', nom: 'Togo'},
    {code: 'TKL', nom: 'Tokelau'},
    {code: 'TON', nom: 'Tonga'},
    {code: 'TTO', nom: 'Trinité-et-Tobago'},
    {"code": "TN", "nom": "Tunisie"},
    {code: 'TUR', nom: 'Turquie'},
    {code: 'TKM', nom: 'Turkménistan'},
    {code: 'TCA', nom: 'Îles Turques et Caïques'},
    {code: 'TUV', nom: 'Tuvalu'},
    {code: 'UGA', nom: 'Ouganda'},
    {code: 'UKR', nom: 'Ukraine'},
    {code: 'ARE', nom: 'Émirats arabes unis'},
    {code: 'GBR', nom: 'Royaume-Uni'},
    {code: 'USA', nom: 'États-Unis'},
    {code: 'UMI', nom: 'Îles mineures éloignées des États-Unis'},
    {code: 'URY', nom: 'Uruguay'},
    {code: 'UZB', nom: 'Ouzbékistan'},
    {code: 'VUT', nom: 'Vanuatu'},
    {code: 'VEN', nom: 'Venezuela, République bolivarienne'},
    {code: 'VNM', nom: 'Viet Nam'},
    {code: 'VGB', nom: 'Îles Vierges britanniques'},
    {code: 'VIR', nom: 'Îles Vierges américaines.'},
    {code: 'WLF', nom: 'Wallis et Futuna'},
    {code: 'ESH', nom: 'Sahara occidental'},
    {code: 'YEM', nom: 'Yémen'},
    {code: 'ZMB', nom: 'Zambie'},
    {code: 'ZWE', nom: 'Zimbabwe'},
];
export default allPays;
